data:
  dataset: fashion_mnist
  data_dir: ./data
  batch_size: 128
  subset_ratio: 1
  test_subset_ratio: 1
  train_split: 1
  augment: false

model:
  name: simple_ffw
  kwargs:
    input_dim: 784 # 28*28
    hidden_dim: 64
    num_classes: 10

loss:
  name: cross_entropy
  kwargs: {}

optim:
  name: sgd
  lr: 0.1
  weight_decay: 0.0005
  momentum: 0.9

trainer:
  max_epochs: 10
  out_dir: runs/debug_run
  seed: 42

cross_validation:
  enabled: true
  n_folds: 1
  seed: 42

regularizers:
  - name: l1
    kwargs: {weight: 0.0}
    grid: [1e-1, 1.0]

analysis:
  collect_activations: true
  layers: 'hidden'
  collect_epochs: 'final'
  activations_filename: activations_collected.csv
  save_per_epoch: true
  save_training_activations: true

visualization:
  enabled: false
  tqdm: true
